### ISSUE TITLE
add link to the last version

### ISSUE THREAD

**Issue by retokromer** [art1pirat/ffv1_factsheet#7]
I guess, on the leaflet there should be added:
- version and/or date of publication
- link to the last PDF version at https://github.com/art1pirat/ffv1_factsheet/blob/master/factsheet_matroska_ffv1_executive_summary.pdf

**Comment by art1pirat** [comment]
Hmm, the date of the build? or the github-commit no?
I rethink about…

**Comment by retokromer** [comment]
I guess, the date of the PDF release would fit. That way one can easily know if his/her leaflet is up-to-date or not.

**Comment by art1pirat** [comment]
ok, compiletime and link to the original source is added :)
